---
- name: Check whether etcd is already installed
  stat:
    path: /etc/systemd/system/etcd.service
  register: etcd_installed

# - name: display etcd version
#   debug:
#     msg: "etcd version is {{ etcd_version }}"

- name: create etcd.sh file
  template:
    src: roles/controller/templates/etcd.sh.j2
    dest: /var/tmp/etcd.sh

- name: install etcd
  command: sh /var/tmp/etcd.sh
  when: etcd_installed.stat.exists == False
