---
- name: get public static IP address for API server
  command: gcloud compute addresses describe k8s-the-easy-way --region us-central1 --format 'value(address)'
  changed_when: false
  register: k8s_api_public_ip

- name: run command to create worker kubeconfig files
  command: kubectl config set-cluster k8s-the-easy-way-2 --certificate-authority=roles/workstation/files/ca.pem --embed-certs=true --server=https://"{{ k8s_api_public_ip.stdout }}":6443 --kubeconfig=roles/worker/files/"{{ item }}".kubeconfig
  args:
    creates: roles/worker/files/"{{ item }}".kubeconfig
  with_items:
    - worker-0
    - worker-1
    - worker-2

- name: run command to set worker kubeconfig credentials
  command: kubectl config set-credentials system:node:"{{ item }}" --client-certificate=roles/worker/files/"{{ item }}".pem --client-key=roles/worker/files/"{{ item }}"-key.pem --embed-certs=true --kubeconfig=roles/worker/files/"{{ item }}".kubeconfig
  changed_when: false
  with_items:
    - worker-0
    - worker-1
    - worker-2

- name: run command to set worker kubeconfig context
  command: kubectl config set-context default --cluster=k8s-the-easy-way-2 --user=system:node:"{{ item }}" --kubeconfig=roles/worker/files/"{{ item }}".kubeconfig
  changed_when: false
  with_items:
    - worker-0
    - worker-1
    - worker-2

- name: use default context
  command: kubectl config use-context default --kubeconfig=roles/worker/files/"{{ item }}".kubeconfig
  changed_when: false
  with_items:
    - worker-0
    - worker-1
    - worker-2

- name: run command to create kube-proxy kubeconfig file
  command: kubectl config set-cluster k8s-the-easy-way-2 --certificate-authority=roles/workstation/files/ca.pem --embed-certs=true --server=https://"{{ k8s_api_public_ip.stdout }}":6443 --kubeconfig=roles/worker/files/kube-proxy.kubeconfig
  args:
    creates: roles/worker/files/kube-proxy.kubeconfig

- name: run command to set kube-proxy kubeconfig credentials
  changed_when: false
  command: kubectl config set-credentials kube-proxy --client-certificate=roles/worker/files/kube-proxy.pem --client-key=roles/worker/files/kube-proxy-key.pem --embed-certs=true --kubeconfig=roles/worker/files/kube-proxy.kubeconfig

- name: run command to set kube-proxy kubeconfig context
  changed_when: false
  command: kubectl config set-context default --cluster=k8s-the-easy-way-2 --user=kube-proxy --kubeconfig=roles/worker/files/kube-proxy.kubeconfig

- name: use default context
  changed_when: false
  command: kubectl config use-context default --kubeconfig=roles/worker/files/kube-proxy.kubeconfig
