---
- name: create SSL certs, kubeconfig files, and configure kubectl locally
  hosts: localhost
  roles:
    - workstation

- name: configure controller nodes
  hosts: tag_controller
  roles:
    - role: controller
      etcd_version: 3.2.6
      kubernetes_version: 1.7.4

- name: configure worker nodes
  hosts: tag_worker
  roles:
    - role: worker
      kubernetes_version: 1.7.4
