---
- name: create worker.sh file
  template:
    src: roles/worker/templates/worker.sh.j2
    dest: /var/tmp/worker.sh

- name: install worker components
  command: sh /var/tmp/worker.sh
  args:
    creates: /etc/systemd/system/kubelet.service
